-- Lesson 02: Restricting and Sorting Data (Part 1_New)

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT DEPARTMENT_ID, LAST_NAME,SALARY,HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME = 'King';

SELECT DEPARTMENT_ID,LAST_NAME,SALARY,HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE = '17-JUN-87';

SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY = 2500;



