-- Lesson 01: Retrieving Data Using the SQL SELECT Statement ( Part 1)


SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT EMPLOYEE_ID FIRST_NAME, LAST_NAME, SALARY 
FROM EMPLOYEES;

SELECT MANAGER_ID, DEPARTMENT_ID FROM DEPARTMENTS;

SELECT SYSDATE
FROM DUAL;

SELECT LAST_NAME, SALARY, JOB_ID, MANAGER_ID, COMMISSION_PCT
FROM EMPLOYEES;

