-- Lesson 02: Restricting and Sorting Data (Part 1_New)

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT DEPARTMENT_ID, LAST_NAME,SALARY,HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME = 'King';

SELECT DEPARTMENT_ID,LAST_NAME,SALARY,HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE = '17-JUN-87';

SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY = 2500;

-- Lesson 02: Restricting and Sorting Data (Part 2_New)

SELECT LAST_NAME,SALARY,JOB_ID
FROM EMPLOYEES
WHERE LAST_NAME != 'King';

SELECT LAST_NAME,SALARY,JOB_ID
FROM EMPLOYEES
WHERE LAST_NAME <> 'King';

SELECT LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 2500 AND 3500;

SELECT LAST_NAME, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '03-Jan-89' AND '21-MAY-91';

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IN (100,102,103);

-- Lesson 02: Restricting and Sorting Data (Part 3_New)

SELECT LAST_NAME,SALARY
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'K%';

SELECT LAST_NAME,SALARY
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%s';

SELECT LAST_NAME,SALARY
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__e%';

-- Lesson 02: Restricting and Sorting Data (Part 3) End

















