-- Lesson 03: Using Single-Row Functions (Part 1)

SELECT LAST_NAME,UPPER(LAST_NAME) AS UNAME,LOWER(LAST_NAME) AS LNAME,
       INITCAP(LAST_NAME) AS INAME
FROM EMPLOYEES
WHERE LOWER(LAST_NAME) = 'King';

SELECT FIRST_NAME,LAST_NAME,FIRST_NAME || ' ' || LAST_NAME AS "Full Name",
       CONCAT(FIRST_NAME,LAST_NAME)
FROM EMPLOYEES;

SELECT LAST_NAME,SUBSTR(LAST_NAME,2,2)
FROM EMPLOYEES;


SELECT LAST_NAME,LENGTH(LAST_NAME)
FROM EMPLOYEES
WHERE LENGTH(LAST_NAME) >= 5;

SELECT LAST_NAME,INSTR(LAST_NAME, ' ')
FROM EMPLOYEES
WHERE INSTR(LAST_NAME, ' ') <>0;

-- Lesson 03: Using Single-Row Functions (Part 2)

SELECT EMPLOYEE_ID,SALARY,LPAD(SALARY,5,'$'),RPAD(SAlARY,6,'$')
FROM EMPLOYEES;

SELECT LAST_NAME,TRIM('K' FROM LAST_NAME)
FROM EMPLOYEES;

SELECT EMPLOYEE_ID,LAST_NAME,JOB_ID,REPLACE(JOB_ID,'_','-')
FROM EMPLOYEES
WHERE REPLACE(JOB_ID,'_','-') LIKE 'AD-%';

SELECT EMPLOYEE_ID,LAST_NAME,JOB_ID,REPLACE(JOB_ID,'_','-') 
FROM EMPLOYEES
WHERE REPLACE(JOB_ID,'_','-') LIKE 'AD-%';

SELECT EMPLOYEE_ID, LAST_NAME,SALARY/3,ROUND(SALARY/3,2),TRUNC(SALARY/3,2)
FROM EMPLOYEES;

SELECT EMPLOYEE_ID,LAST_NAME,MOD(SALARY,3)
FROM EMPLOYEES;

-- Lesson 03: Using Single-Row Functions (Part 3)

SELECT SYSDATE,ADD_MONTHS(SYSDATE,2),ADD_MONTHS(SYSDATE,-1),ADD_MONTHS(SYSDATE,2*12)
FROM DUAL;