-- Lesson 01: Retrieving Data Using the SQL SELECT Statement ( Part 1)


SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT EMPLOYEE_ID FIRST_NAME, LAST_NAME, SALARY 
FROM EMPLOYEES;

SELECT MANAGER_ID, DEPARTMENT_ID FROM DEPARTMENTS;

SELECT SYSDATE
FROM DUAL;

SELECT LAST_NAME, SALARY, JOB_ID, MANAGER_ID, COMMISSION_PCT
FROM EMPLOYEES;

-- Lesson 01: Retrieving Data Using the SQL SELECT Statement ( Part 2)

SELECT LAST_NAME, SALARY, COMMISSION_PCT,
       NVL(COMMISSION_PCT,0)*SALARY+12 AS Totalsalary
FROM EMPLOYEES;

SELECT EMPLOYEE_ID AS "EMP#",LAST_NAME "Name",SALARY AS "Total salary",
       COMMISSION_PCT AS "Comm salary"
FROM EMPLOYEES;


